refactor math package
bleu-studio/balancer-tools pull request #156
Opened 2023-07-13 16:07 UTC by yvesfracari

Refactor math package to be more generic. The idea is to design the AMM class to be generic and receive multiple kinds of Pools (or math implementations). Also, some parts of our code were replaced for Balancer-sor implementation (such as the rates part).

2023-07-19 12:31 UTC, luizakp requested changes
Great job, @yvesfracari !

We just missed something on the math side during the refactor. I just cross-checked the same from production and from your branch and I got different results (maybe my branch is not entirely up to date due to the rebase to rewrite the commit history):

Production:
<img width="1200" alt="image" src="https://github.com/bleu-studio/balancer-tools/assets/63298341/c7aae720-5931-455c-aa4d-0cfc316ee1c8">

<img width="1200" alt="image" src="https://github.com/bleu-studio/balancer-tools/assets/63298341/dd742cb7-7de5-4262-8c5a-6bd901c0897d">


Localhost:
<img width="1200" alt="image" src="https://github.com/bleu-studio/balancer-tools/assets/63298341/a7def601-3c3a-47c7-a390-d2d07a024db9">

<img width="1200" alt="image" src="https://github.com/bleu-studio/balancer-tools/assets/63298341/8bd3f2af-0050-4491-9082-a449dee85178">

2023-07-19 12:31 UTC, luizakp commented on packages/math-new/classes.svg
maybe we should have a readme for the math to display this

2023-07-19 12:31 UTC, luizakp commented on packages/math-new/src/index.ts
> +  priceImpactForExactTokenOutReversedSwap(
all the AMM should have this function as a common point or this is just the example?

2023-07-20 14:21 UTC, ribeirojose submitted a review, later dismissed
a bit hard to review in detail, but looking good overall

2023-07-20 19:14 UTC, merged