[APR] Pool TVL for a especific round
bleu-studio/balancer-tools pull request #219
Opened 2023-08-18 03:42 UTC by Rawallon

2023-08-18 13:43 UTC, ribeirojose commented on apps/balancer-tools/src/app/apr/(utils)/balancerAPI.ts
>        BALANCER_GRAPHQL_API_URL,
Just remember you'll also need to query the correct subgraph based on the chain that pool is in.

2023-08-18 13:44 UTC, ribeirojose requested changes
This is looking good -- but the pattern we've followed is to create a query under /gql and call the generator. That way you'll have access to the hooks and fetcher directly in all chains that we support. I can show you around there but @luizakp and @devjoaov are also familiar with it FYI

2023-08-18 22:32 UTC, luizakp commented
> This is looking good -- but the pattern we've followed is to create a query under /gql and call the generator. That way you'll have access to the hooks and fetcher directly in all chains that we support. I can show you around there but @luizakp and @devjoaov are also familiar with it FYI

It looks like gql generated functions are all client side 🤔

2023-08-19 01:15 UTC, luizakp commented
> you can ask @mendesfabio for the blocks endpoints -- but did you search for them anywhere? You can find them in somewhere in Balancer's frontend config as well

They are empty on Balancer's frontend @ribeirojose. Created a [task for this](https://linear.app/bleu-llc/issue/BAL-659/add-sepolia-gnosis-and-optimism-subgraph-on-subgraphchainsblocks)

[Sepolia](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/sepolia/index.ts#L37)
[Optimism](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/optimism/index.ts#L36)
[Gnosis](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/gnosis-chain/index.ts#L39)

2023-08-21 13:01 UTC, ribeirojose commented
> > you can ask @mendesfabio for the blocks endpoints -- but did you search for them anywhere? You can find them in somewhere in Balancer's frontend config as well
> 
> They are empty on Balancer's frontend @ribeirojose. Created a [task for this](https://linear.app/bleu-llc/issue/BAL-659/add-sepolia-gnosis-and-optimism-subgraph-on-subgraphchainsblocks)
> 
> [Sepolia](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/sepolia/index.ts#L37) [Optimism](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/optimism/index.ts#L36) [Gnosis](https://github.com/balancer/frontend-v2/blob/46df6c2d6178236291196320447f6e217b500cd6/src/lib/config/gnosis-chain/index.ts#L39)

https://linear.app/bleu-llc/issue/BAL-659#comment-dadd94c2

2023-08-21 14:59 UTC, merged